accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'
urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^recommendation/$', views.predict_recomm, name='recommendation'),
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileDetailView.as_view(), name='profile'),
    # url(r'^recommendation/(?P<pk>\d+)/$', views.RecommendationDetailView.as_view(), name='recommendation'),
#url(r'^profile/(?P<pk>\d+)/edit/$', views.profile_update, name='edit_profile'),
]

heart_disease_prediction/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from accounts.views import Aboutpageview,Intropageview
from accounts import views
from heart_disease_prediction import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.user_login,name='user_login'),
    url(r'^about/',Aboutpageview.as_view(),name='about'),
    url(r'^intro/',Intropageview.as_view(),name='intro'),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^predict/',include('predict_risk.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predict_risk/urls.py
from django.conf.urls import url
from . import views
app_name='predict'
urlpatterns=[
url(r'^(?P<pk>\d+)$',views.PredictRisk,name='predict'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf.urls import url
from django.shortcuts import resolve_url


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    profile_pic = models.ImageField(upload_to='profile_pics', default="1.jpg")

    def __str__(self):
        return self.user.username

# Create your models here.

accounts/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter username'}
    ), required=True, max_length=50)

    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Email Id'}
    ), required=True, max_length=50)

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter password'}
    ), required=True, max_length=50)

    confirm_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Confirm password'}
    ), required=True, max_length=50)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Password and Confirm password does not match")


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('profile_pic',)


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        widgets = {'username': forms.TextInput(attrs={'readonly': 'True'})}

accounts/views.py
from django.shortcuts import render, get_object_or_404
from .forms import UserForm, UserProfileInfoForm, UpdateProfileForm
from django.views.generic import DetailView,UpdateView,TemplateView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import UserProfileInfo, User
import random

# Create your views here.

@login_required
def user_logout(request):
    #del request.session['user_id']
    request.session.flush()
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))

class Aboutpageview(TemplateView):
    template_name='accounts/about.html';


class Intropageview(TemplateView):
    template_name='accounts/intro.html';

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

        if registered:
            return HttpResponseRedirect(reverse('user_login'))

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'accounts/register.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                request.session['user_id'] = user.profile.pk

                return HttpResponseRedirect(reverse('predict:predict', kwargs={'pk': user.profile.pk}))
            else:
                return HttpResponse("Account not active")
        else:
            print("Tried login and failed")
            print("username: {} and password: {}".format(username, password))
            # return HttpResponse("Invalid login details supplied!")
            return render(request, 'accounts/invalidLogin.html', {})

    else:
        return render(request, 'accounts/login.html', {})

class ProfileDetailView(LoginRequiredMixin, DetailView):
    login_url = '/'
    redirect_field_name = '/'
    model = UserProfileInfo
    template_name = 'accounts/profileview.html'

    def get_context_data(self, **kwargs):
        if self.request.session.has_key('user_id'):
            u_id = self.request.session['user_id']
            context = super(ProfileDetailView, self).get_context_data(**kwargs)
            context['user_id'] = u_id

        return context

name = ['Name: '
        'Name: Dr. A K Bardhan',
        'Name: Dr. Siddhartha Mani',
        'Name: Dr. Jayanta Saha',
        'Name: Dr. Indranil Dutta',
        'Name: Dr. Aftab Khan',
        'Name: Dr. Parijat Deb Choudhury',
        'Name: Dr Soumitra Kumar',
        'Name: Dr. Arvind Kumar',
        'Name: Dr Suchit Majumdar',
        'Name: Dr Kunal Sarkar',
        'Name: Dr. Amal Kumar Khan',
        'Name: Dr Arindam Pande',
        'Name: Dr Rabin Chakraborty',
        'Name: Dr K S Poddar MD DM',
        'Name: Dr. Arup Dasbiswas',
        'Name: Dr. Debashis Ghosh',
        'Name: Dr Prakash Chandra Mandal',
        'Name: Dr Rajkumar Dutta',
        'Name: Dr. Sankha Subhra Das',
        'Name: Dr Anil Mishra',
        'Name: Dr. Indranil Dutta',
        'Name: Dr. Sunando Adhikari',
        'Name: Dr Achyut Sarkar',
        'Name: Dr Sunil Lhila',
        'Name: Dr. Dhiman Kahali',
        'Name: Dr Dilip Kumar',
        'Name: Dr Sankar Kumar Chatterjee']

rating = ["Rating: "
        "Rating: 4.5",
         "Rating: 4.7",
         "Rating: 2.5",
         "Rating: 4.5",
         "Rating: 4.8",
         "Rating: 5",
         "Rating: 4.5",
         "Rating: 4.2",
         "Rating: 4.2",
         "Rating: 3.8",
         "Rating: 3.4",
         "Rating: 4.9",
         "Rating: 3.2",
         "Rating: 4.4",
         "Rating: 2.9",
         "Rating: 3.7",
         "Rating: 4.2",
         "Rating: 4.8",
         "Rating: 5",
         "Rating: 3.2",
         "Rating: 4.5",
         "Rating: 5",
         "Rating: 4.3",
         "Rating: 4.7",
         "Rating: 4.5",
         "Rating: 4.7",
         "Rating: 4.8",
         ]


contact = ["Contact No: ",
            "Contact No: 1860 500 1066",
          "Contact No: 098318 94526",
          "Contact No: 1860 500 1066",
          "Contact No: 1860 500 4916",
          "Contact No: 1860 500 1066",
          "Contact No: 033 4058 5544",
          "Contact No: 082320 32519",
          "Contact No: 1860 500 4916",
          "Contact No: 090518 83987",
          "Contact No: 098316 26553",
          "Contact No: 033 2563 1855",
          "Contact No: 090380 64946",
          "Contact No: 098363 70453",
          "Contact No: 094330 89596",
          "Contact No: 070023 18894",
          "Contact No: 1860 500 1066",
          "Contact No: 098317 41032",
          "Contact No: 033 2564 7944",
          "Contact No: 033 6540 2963",
          "Contact No: 033 4450 4145",
          "Contact No: 1860 500 4916",
          "Contact No: 1860 500 1066",
          "Contact No: 033 2223 5181",
          "Contact No: 033 7122 2222",
          "Contact No: 033 3040 3355",
          "Contact No: 092300 90526",
          "Contact No: 098300 33677",
          ]


address = ["Address: ",
            "Address: Apollo Gleneagles Hospital Limited, 58, Canal Circular Rd, Kadapara, Phool Bagan, Kankurgachi, Kolkata, West Bengal 700054",
          "Address: 124, Eastern Metropolitan Bypass, Mukundapur Market, Stadium Colony, Mukundapur, Kolkata, West Bengal 700099",
          "Address: 33-42, Ground Floor, The Galleria - Dlf, Plot No BG-8, Apollo Clinic, Action Area 1B, Newtown, Kolkata, West Bengal 700156",
          "Address: P 72, Prince Anwar Shah Road, Opp. South City Mall, CIT Scheme 114 B Apollo Clinic, Prince Anwar Shah Rd, Kolkata, West Bengal 700045",
          "Address: Apollo Gleneagles Hospital Limited, 58, Canal Circular Rd, Kadapara, Phool Bagan, Kankurgachi, Kolkata, West Bengal 700075",
          "Address: 1412, Medithics Clinic, near R. N. Tagore Hospital, Mukundapur, Kolkata, West Bengal 700099",
          "Address: P-273, Bangur Avenue, Block A, Ballygunge, Kolkata, West Bengal 700055",
          "Address: P 72, Prince Anwar Shah Road, Opp. South City Mall, CIT Scheme 114 B Apollo Clinic, Prince Anwar Shah Rd, Kolkata, West Bengal 700045",
          "Address: 58, Canal Circular Road apollo hospital, Kadapara, Phool Bagan, Kolkata, West Bengal 700054",
          "Address: Attached with Medica Hospital, 42/1A, Harish Mukherjee Rd, Bhowanipore, Kolkata, West Bengal 700025",
          "Address: 11 No, Bus Stop, 29, Barrackpore Trunk Rd, Manasbag, Belghoria, Kolkata, West Bengal 700056",
          "Address: 48/2b, Barrackpore Trunk Rd, South Sinthee, University Of Calcutta, Sinthee, Kolkata, West Bengal 700050",
          "Address: BE-407, BE Block, Sector 1, Bidhannagar, Kolkata, West Bengal 700064",
          "Address: 52, Dr SP Mukherjee Rd, Mahendra Colony, Cantonment, Rajbari, Dum Dum, Kolkata, West Bengal 700028",
          "Address: C.I.T. Road Scheme, Paddapukur, Entally, Kolkata, West Bengal 700014",
          "Address: Apollo Gleneagles Hospital Limited, 58, Canal Circular Rd, Kadapara, Phool Bagan, Kankurgachi, Kolkata, West Bengal 700054",
          "Address: 64/1/16A, Khudiram Bose Sarani, Kolkata, West Bengal 700037",
          "Address: 6, M M Feeder Road, Ariadaha P O, Kolkata, West Bengal 700057",
          "Address: Apollo Gleneagles Hospital Limited, 58, Canal Circular Rd, Kadapara, Phool Bagan, Kankurgachi, Kolkata, West Bengal 700054",
          "Address: Alipore, Kolkata, West Bengal 700027",
          "Address: P 72, Prince Anwar Shah Road, Opp. South City Mall, CIT Scheme 114 B Apollo Clinic, Prince Anwar Shah Rd, Kolkata, West Bengal 700045",
          "Address: 33-42, Ground Floor, The Galleria - Dlf, Plot No BG-8, Apollo Clinic, Action Area 1B, Newtown, Kolkata, West Bengal 700156",
          "Address: IPGMER & SSKM Hospital, 244 A, J C Bose Road, Kolkata, West Bengal 700020",
          "Address: 124, Mukundapur, E M Bypass, Kolkata, West Bengal 700099",
          "Address: 1, 1, National Library Ave, Alipore, Kolkata, West Bengal 700027",
          "Address: Medica Superspecialty Hospital, 127, Eastern Metropolitan Bypass, Nitai Nagar, Mukundapur, Kolkata, West Bengal 700099",
          "Address: Blind School, 19/2, Dr Akshay Kumar Paul Rd, Opp:, Behala, Kolkata, West Bengal 700034"
          ]


def predict_recomm(request):
        value1 =random.randint(1, 10)
        value2 =random.randint(11, 20)
        value3 =random.randint(21, 25)
        value4 =random.randint(1, 26)


        # for num in range(100):
        names1 = name[value1]
        ratings1 = rating[value1]
        contacts1 = contact[value1]
        addresses1 = address[value1]



        names2 = name[value2]
        ratings2 = rating[value2]
        contacts2 = contact[value2]
        addresses2 = address[value2]



        names3 = name[value3]
        ratings3 = rating[value3]
        contacts3 = contact[value3]
        addresses3 = address[value3]


        names4 = name[value4]
        ratings4 = rating[value4]
        contacts4 = contact[value4]

accounts/templates/accounts/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />
    <meta charset="UTF-8">
    <title>ABOUT</title>
</head>


<body class="landing-page sidebar-collapse">
<!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent" color-on-scroll="400">
        <div class="container">
            <div class="navbar-translate">
                <a class="navbar-brand" >
                    Heart Disease Analysis &amp; Prediction
                </a>
            </div>
            <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="">
                <ul class="navbar-nav">
                    <li class="nav-item" style="display: inline-block">
                      {%if user.is_authenticated %}
                        <a class="nav-link " href="{% url 'intro' %}">Introduction</a> <br>
                        <a class="nav-link " href="{% url 'accounts:logout'%}">Logout</a>
                        {%else%}
                        {%endif%}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->

    <div class="wrapper">
        <div class="page-header page-header-small ">
            <div class="page-header-image" data-parallax="true" style="background-image: url('{% static 'images/image99.jpg' %}');">
            </div>
            <div class="container">
                <div class="content-center">
                    <h1 class="title">Predict your chance of having a heart disease because prevention is better than cure!</h1>
                    <div class="text-center">
                        <a href="{% url 'accounts:register' %}" class="btn btn-danger border btn-round">
                            <h6>Signup</h6>
                        </a>
                        <br>
                        <a href="{% url 'user_login' %}" class="btn btn-danger border btn-round">
                            <h6>Login</h6>
                        </a>
                    </div>
                </div>
            </div>
        </div>


        <div class="section section-about-us">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 ml-auto mr-auto text-center">
                        <h2 class="title">About Us</h2>
                        <h5 class="description"><strong>Loads of features. Making it easier for anyone to predict the chance of getting heart disease. Shows analysis done on large data sets.</strong></h5>
                    </div>
                </div>
                <div class="separator separator-primary"></div>
                <div class="section-story-overview">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="image-container image-left" style="background-image: url('{% static 'images/1.jpg' %}')">
                                <!-- First image on the left side -->
                                <p class="blockquote blockquote-primary">"65% of medical professionals believe increased technology adoption will result in better patient outcome."
                                    <br>
                                    <br>
                                    <small>– GERMAIN CHASTEL,<br>CEO and Founder of NewtonX.</br></small>
                                </p>
                            </div>
                            <!-- Second image on the left side of the article -->
                            <div class="image-container" style="background-image: url('{% static 'images/django2.jpg' %}')"></div>
                        </div>
                        <div class="col-md-5">
                            <!-- First image on the right side, above the article -->
                            <div class="image-container image-right" style="background-image: url('{% static 'images/heart.jpg' %}')"></div>
                            <h3 style="color:blue">Vast and Reliable Dataset</h3>
                            <p> This database contains 76 attributes, but all published experiments refer to using a subset of 14 of them. In particular, the Cleveland database is the only one that has been used by ML researchers to this date.
                            </p>
                            <br>
                            <br>
                            <br>
                            <br>
                              <h3 style="color:blue">Analysis & Prediction Using Python and Django Framework</h3>
                            <p>The code used for analysis of data and getting prediction rates is pretty simple. The code is written in Python and Django at Atom platfrom.
                            </p>
                        </div>


                    </div>
                </div>
            </div>
        </div>

        <div class="section section-team text-center">
            <div class="container">
                <h2 class="title">Here is our team</h2>
                <div class="team">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="team-player">
                              <img src="{% static 'images/Prafull2.jpeg' %}" alt="Thumbnail Image" class="rounded-circle img-fluid img-raised">
                                <h4 class="title">Prafull Kumar</h4>
                                <p class="category text-primary">Student<br>CSE2(4th year)</p>
                                <a href="https://github.com/codeFriend7/" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-github"></i></a>
                                <a href="https://www.facebook.com/prafull.kumar.54584" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-facebook-square"></i></a>
                                <a href="https://www.instagram.com/prafull_kumar7/" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="team-player">
                                <img src="{% static 'images/Priyam.jpeg' %}" alt="Thumbnail Image" class="rounded-circle img-fluid img-raised">
                                <h4 class="title">Priyam Halder</h4>
                                <p class="category text-primary">Student<br>CSE2(4th year)</p>
                                <a href="https://github.com/codeFriend7/" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-github"></i></a>
                                <a href="https://www.facebook.com/babai.halder.56884761" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-facebook-square"></i></a>
                                <a href="https://www.instagram.com/priyam_yo/?igshid=z4q8eucbd1z3" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="team-player">
                                <img src="{% static 'images/Ritambhara.jpeg' %}" alt="Thumbnail Image" class="rounded-circle img-fluid img-raised">
                                <h4 class="title">Ritambhara Chatterjee</h4>
                                <p class="category text-primary">Student<br>CSE2(4th year)</p>
                                <a href="https://github.com/codeFriend7/" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-github"></i></a>
                                <a href="https://www.facebook.com/ritambhara.chatterjee" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-facebook-square"></i></a>
                                <a href="https://www.instagram.com/ritambhara_rc_26/?igshid=yke3x73h1ldn" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="team-player">
                                <img src="{% static 'images/Rupak.jpeg' %}" alt="Thumbnail Image" class="rounded-circle img-fluid  img-raised">
                                <h4 class="title">Rupak Dey</h4>
                                <p class="category text-primary">Student<br>CSE2(4th year)</p>
                                <a href="https://github.com/Rupak240" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-github"></i></a>
                                <a href="https://www.facebook.com/rupak.dey.94849" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-facebook-square"></i></a>
                                <a href="" class="btn btn-primary btn-icon btn-round"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>


                        <div class="col-md-6">
                          <div class="team-player">
                                <img src="{% static 'images/Sampriti.jpeg' %}" alt="Thumbnail Image" class="rounded-circle img-fluid  img-raised">
                                <h4 class="title">Sampriti Ghosh</h4>
                                <p class="category text-primary">Student<br>CSE2(4th year)</p>
                                <a href="https://github.com/codeFriend7/" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-github"></i></a>
                                <a href="https://www.facebook.com/sampriti.ghosh.313" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-facebook-square"></i></a>
                                <a href="https://www.instagram.com/sg060399/?igshid=1dk0o40gj90so" target="_blank" class="btn btn-primary btn-icon btn-round"><i class="fa fa-instagram"></i></a>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="footer footer-default">
            <div class="container">

                <div class="about-us" data-aos="fade-right" data-aos-delay="200">
                    <p> <a href="{% url 'user_login' %}">Login</a>  |  <a href="{% url 'intro' %}">Introduction</a>  |  <a href="{% url 'about' %}">About</a></p>
                </div>
                <p></p>
                <p>  </p>
                <p></p>
                <div class="copyright">
                   Coded by Prafull, Priyam, Ritambhara, Rupak and Sampriti
                </div>
            </div>
            <div class="move-up">
                <span><i class="fas fa-arrow-circle-up fa-2x"></i></span>
            </div>
        </footer>

        <!-- <footer class="footer footer-default">
            <div class="container">
                <nav>

                </nav>
                <div class="copyright">
                   Coded by Prafull,Priyam,Ritambhara,Rupak and Sampriti
                </div>
            </div>
        </footer> -->

    </div>

</body>
<script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap_ui_kit.js' %}" type="text/javascript"></script>
</html>

accounts/templates/accounts/invalidLogin.html
<!-- <!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Invalid Login</title>
  </head>
  <body>
    <div class="container">
      <h1>Invalid Login details supplied!!</h1>
    </div>
  </body>
</html> -->
















<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Invalid Login</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900" rel="stylesheet">

	<!-- Custom stlylesheet -->
  <link href="{% static 'css/invalidLogin.css' %}" rel="stylesheet" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
			</div>
			<h1 class="heading">Invalid Login details supplied!!</h1>
			<!-- <h2>Invalid Login details supplied!!</h2> -->
			<!-- <p>The page you are looking for might have been removed had its name changed or is temporarily unavailable.</p> -->
      <!-- <p>This page can’t be reached!</p> -->
			<a href="{% url 'accounts:register' %}">Signup</a>
      <a href="{% url 'user_login' %}">Back to Login</a>
		</div>
	</div>

</body>

</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'><!--web font-->
    <link rel="icon" type="image/jpg"  href="{% static 'images/logo.jpg' %}">
    <title>Heart disease prediction</title>
</head>
<body>
	<div class="agileits-main">
	<div class="w3top-nav">

				<div class="w3top-nav-left">
					<h1 style="color:white;">          Heart Disease Prediction System</h1>
				</div>

				<div class="w3top-nav-right">
					<ul>
            <li><a href="{% url 'intro' %}">Introduction</a></li>
						<li><a href="{% url 'about' %}">About</a></li>
						<li><a href="{% url 'accounts:register' %}">Signup</a></li>
						<li><a href="/admin">Admin login</a></li>
					</ul>
				</div>

		</div>




    <div class="header-main">
      {% if user.is_authenticated %}
        <h2>You are already logged in !!</h2>
        <button class="btn btn-neutral"><a href="{% url 'accounts:logout'%}">Logout</a></button>
      {% else %}
    <h2>Login Now</h2>
			<div class="header-bottom">
				<div class="header-right w3agile">
					<div class="header-left-bottom agileinfo">
            <form role="form" action=" {% url 'user_login' %}" method="post">
            {% csrf_token %}
							<div class="icon1">
								<input type="text" name="username" placeholder="Username" >
							</div>
							<div class="icon1">
								<input type="password"  name="password" placeholder="Password"/>
							</div>
							<div class="bottom">
								<input type="submit" value="Log in">
							</div>
					</form>
					</div>
				</div>
			</div>
	</div>

	</div>
  {% endif %}
</body>

</html>